[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "paramforge"
version = "1.0.0"
description = "Advanced URL Parameter Discovery & Recon Intelligence Framework"
readme = "README.md"
requires-python = ">=3.11"
authors = [{name = "Mr Dinesh Pathro"}]
dependencies = ["typer>=0.9", "rich>=13", "httpx>=0.25", "beautifulsoup4>=4.12", "PyYAML>=6"]

[project.scripts]
paramforge = "paramforge.cli:app"

[tool.setuptools.packages.find]
where = ["src"]
